### PR TITLE
MvvmCross 4.0.0

### PR DESCRIPTION
**Pull request by gentledepp**
I upgraded the packages and the nuspec to require MvvmCross 4.0.0
Unfortunately, I had to remove the strong naming, as MvvmCross assemblies do not have a strong name anymore

### CODE REVIEW

**Comment by tillig** [comment]
Looks like there are a few conflicts to resolve before we can take a look here.

**Comment by markmadlangbayan** [comment]
Hello, any progress with this?

**Comment by gentledepp** [comment]
Sorry - habe been lazy the last weekends :-|
But I'll try to fix it this one.

**Comment by markmadlangbayan** [comment]
Thanks Alexander!  Looking forward on using this.

**Comment by gentledepp** [comment]
One thing I absolutely HATE about appveyor is that it only tells me that "all checks have failed", but for some reason, it does not give me any details.
So I am totally blind here guys... Could anyone help me out and tell me where I find more detailed explanation for the failed build, please?

**Comment by tillig** [comment]
Currently the problem isn't that AppVeyor is failing the build - it's that there are merge conflicts that are stopping the build from even beginning. Note the "This branch has conflicts that must be resolved - use the command line to resolve conflicts before continuing" message. I believe that once the merge conflicts are resolved the build will be able to proceed. When it does build, I think you'll see the build show up [in the Autofac MvvmCross build history](https://ci.appveyor.com/project/Autofac/autofac-extras-mvvmcross/history) so you can troubleshoot from there.

**Comment by gentledepp** [comment]
Well guys... what is going on.
It appears to me that you started to convert the whole project to use the new .NET Core framework stuff and apparently I cannot event get the "develop" branch to build on my machine.
It fails with loats of bizarre errors like "the type void is not defined" and stuff.
Can you give me any hint in how to make this work?

<pre>
...
2>D:\Code\Autofac.Extras.MvvmCross_gd\test\Autofac.Extras.MvvmCross.Test\AutofacMvxIocProviderFixture.cs(199,20,199,49): DNX Core 5.0 error CS0518: Predefined type 'System.Object' is not defined or imported
2>D:\Code\Autofac.Extras.MvvmCross_gd\test\Autofac.Extras.MvvmCross.Test\AutofacMvxIocProviderFixture.cs(199,13,199,49): DNX Core 5.0 error CS0012: The type 'Action' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
2>D:\Code\Autofac.Extras.MvvmCross_gd\test\Autofac.Extras.MvvmCross.Test\AutofacMvxIocProviderFixture.cs(199,13,199,49): DNX Core 5.0 error CS0012: The type 'Func<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
2>D:\Code\Autofac.Extras.MvvmCross_gd\test\Autofac.Extras.MvvmCross.Test\AutofacMvxIocProviderFixture.cs(200,13,200,19): DNX Core 5.0 error CS0518: Predefined type 'System.Object' is not defined or imported
2>D:\Code\Autofac.Extras.MvvmCross_gd\test\Autofac.Extras.MvvmCross.Test\AutofacMvxIocProviderFixture.cs(200,27,200,48): DNX Core 5.0 error CS0518: Predefined type 'System.Object' is not defined or imported
2>D:\Code\Autofac.Extras.MvvmCross_gd\test\Autofac.Extras.MvvmCross.Test\AutofacMvxIocProviderFixture.cs(200,27,200,48): DNX Core 5.0 error CS0246: The type or namespace name 'ArgumentNullException' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Code\Autofac.Extras.MvvmCross_gd\test\Autofac.Extras.MvvmCross.Test\AutofacMvxIocProviderFixture.cs(200,20,200,49): DNX Core 5.0 error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
2>D:\Code\Autofac.Extras.MvvmCross_gd\test\Autofac.Extras.MvvmCross.Test\AutofacMvxIocProviderFixture.cs(200,20,200,49): DNX Core 5.0 error CS0518: Predefined type 'System.Object' is not defined or imported
2>D:\Code\Autofac.Extras.MvvmCross_gd\test\Autofac.Extras.MvvmCross.Test\AutofacMvxIocProviderFixture.cs(200,13,200,49): DNX Core 5.0 error CS0012: The type 'Action' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
2>D:\Code\Autofac.Extras.MvvmCross_gd\test\Autofac.Extras.MvvmCross.Test\AutofacMvxIocProviderFixture.cs(200,13,200,49): DNX Core 5.0 error CS0012: The type 'Func<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
2>D:\Code\Autofac.Extras.MvvmCross_gd\test\Autofac.Extras.MvvmCross.Test\AutofacMvxIocProviderFixture.cs(205,23,205,30): DNX Core 5.0 error CS0518: Predefined type 'System.Object' is not defined or imported
2>D:\Code\Autofac.Extras.MvvmCross_gd\test\Autofac.Extras.MvvmCross.Test\AutofacMvxIocProviderFixture.cs(205,23,205,30): DNX Core 5.0 error CS0518: Predefined type 'System.Object' is not defined or imported
2>D:\Code\Autofac.Extras.MvvmCross_gd\test\Autofac.Extras.MvvmCross.Test\AutofacMvxIocProviderFixture.cs(205,23,205,30): DNX Core 5.0 error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
2>D:\Code\Autofac.Extras.MvvmCross_gd\test\Autofac.Extras.MvvmCross.Test\AutofacMvxIocProviderFixture.cs(205,23,205,30): DNX Core 5.0 error CS0518: Predefined type 'System.Object' is not defined or imported
2>D:\Code\Autofac.Extras.MvvmCross_gd\test\Autofac.Extras.MvvmCross.Test\AutofacMvxIocProviderFixture.cs(205,13,205,30): DNX Core 5.0 error CS0518: Predefined type 'System.Void' is not defined or imported
2>D:\Code\Autofac.Extras.MvvmCross_gd\test\Autofac.Extras.MvvmCross.Test\AutofacMvxIocProviderFixture.cs(212,23,212,31): DNX Core 5.0 error CS1729: 'object' does not contain a constructor that takes 0 arguments
2>
2>  Build failed.
2>           0 Warning(s).
2>         529 Error(s).
2>
2>  Time elapsed 00:00:00.2893486
2>
========== Rebuild All: 0 succeeded, 2 failed, 0 skipped ==========
</pre>

I am running the latest version of vs2015.
Also I get these reference errors dispalyed in solution explorer and I do not quite know how to handle these.... Any advises?
[https://onedrive.live.com/redir?resid=7F3CBB45213A5B15!5106&authkey=!AMDb-7_uNlF3Iwg&v=3&ithint=photo%2cpng](url)

**Comment by tillig** [comment]
Thanks for this PR! Sorry it took so long to get moving here, but we do appreciate the work.

I've not pulled directly, but I did take the interfaces and the work done here as the basis for updating the project now that .NET Core RTM is out. I have it working now with both MvvmCross 4 and Autofac 4, plus property injection ability using a new property selection mechanism we've added in Autofac 4.

**Pull request closed without merging**
