### PR TITLE
Working MvvmCross 4.0.0

### PR DESCRIPTION
**Pull request by promontis**
Fixing the build error this repo was having duo a merge conflict.

### CODE REVIEW

**Comment by promontis** [comment]
So, this project was using the dnx as its build environment... wouldn't recommend that for mvvmcross, since xamarin doesn't really support xproj and project.json. 

Any autofac members willing to comment on this PR? If it's ok, then please merge and push nuget packages

**Comment by alexmg** [comment]
How the package gets built shouldn't matter in regards to Xamarin support. It's the supported target frameworks in the resulting package that matter. It looks like MvvmCross added support for dotnet 5.0 in the last package. I suppose they will be looking to migrate that to netstandard soon.

I know @tillig was trying to get some of these smaller packages over to the new DNX build but now that will need to be CLI instead. I just commented on another issue that it would be nice to have proper AppVeyor support for CLI builds so we can go back to having a simple `appveyor.yml` file and let the CI take care of the rest. That was one of the biggest bonuses we got when splitting out all the different packages to individual repositories.

I took a quick glance over the actual code changes and they look to be fine, but I would like to see this move forward towards CLI now that Microsoft has apparently stabilized on that. I'm not sure how far off proper support for CLI builds on AppVeyor is.

Thanks for getting this update together. Once we decide what to do on the build front we can get this nice PR merged in.

**Comment by promontis** [comment]
Yeah, if the build outputs xamarin supported dlls, it's fine by me... it's just that xproj are but problematic in xamarin studio right now.  

Anyhow, we've just added support for netstandard in the nuspec files. We're also going to convert the projects to netstandard... don't know when that will happen though.

I agree that we should work towards netstandard and CLI. This probably isn't the right place to discuss that change... shall I create an issue for this? 

I think the best thing to do right now is to get a build up and running that is compatible with MvvmCross 4, whether that is via DNX or not. Most people are all using that version and otherwise this repo is of no more use (which is a shame because autofac is awesome). What do you think?

**Comment by tillig** [comment]
Thanks for this PR! We appreciate the work. Since a lot has changed for .NET Core RTM I'm not able to directly pull it, but I'm taking the interfaces and the work and porting it over. I have it working now with both MvvmCross 4 and Autofac 4, plus property injection ability using a new property selection mechanism we've added in Autofac 4.

**Pull request closed without merging**
