### PR TITLE
Update packages and add deprecation-note

### PR DESCRIPTION
**Pull request by alsami**
* Update and limit dependency of `Autofac`
* Add deprecation note in `readme.md`
* Update `appveyor.yml`
* Add fixed package-icon

### CODE REVIEW

**Comment by tillig** [comment]
This looks good - is this PR going to get the icon or is that a separate PR? Just curious if I should wait before pulling this in.

**Comment by alsami** [comment]
Yes, please wait, will do so soon.

**Comment by alsami** [comment]
Good to go I think :)

**Review by tillig — APPROVED** [review]
Awesome! And awaaaaaaaay we go!

**Pull request merged**
