### PR TITLE
Singleton mvxicoconstruct

### PR DESCRIPTION
**Pull request by gentledepp**
Fixing issue #5 

Allows to construct types like we are used in MvvmCross:

Mvx.IocConstruct<MyType>()

Note: "MyType" does not have to be registered yet, when using IocConstruct. It is registered implicitly if required.

### CODE REVIEW

**Comment by tillig** [comment]
Hey, thanks for the help! Unfortunately, I don't think I'll be able to take the pull request as it sits. It appears maybe you didn't pull in all the changes from the latest develop branch before submitting the request. For example, I see a lot of changes in this PR about adding in property injection support, but that was already done a while ago. If done right, the only differences we'll see in the list of files changed are the differences due to things you did.

If you can update the PR so it only contains _your_ changes, we'd be happy to take a look.

**Comment by gentledepp** [comment]
Hi!
Actually you did not take my original PR months before because you guys migrated to the new xproj format for whatever reason.
So I pulled your last dev-branch changes and merged myself. That's why there is so many changes.

It already took me several hours to merge and get the tests to run while VS2015 refused to even find the unittests so I had to run them via the console without debugging, cot a compile error for a "trailing whitespace" that visual studio (NOT ME!!) added and what not.

So I hope you understand that I am not willing to go through all that trouble again because you guys do not like the "version log". :-|

I'll rather keep my version then and publish another nuget for MvvmCross users thereby extending todays nuget dependency hell 💃

**Comment by tillig** [comment]
Well, unfortunately we can't accept the PR in the format it is. If you choose to fork and go your own way, it would be unfortunate but that's your prerogative.

**Comment by gentledepp** [comment]
In case I find time (sorry, but I never did anything like that) what'd be the steps to do to get rid of those checkins? (is there a tutorial or something?)

**Comment by tillig** [comment]
I'm not sure what status your repo/fork/branch is in. The first step would be getting your repo into the same state as ours - using our build, using our project/solution structure, etc.

If you search around on Google you can find answers to a lot of questions, like...
- [How do you update a pull request?](http://stackoverflow.com/questions/9790448/how-to-update-a-pull-request)
- [How do I synchronize a fork?](https://help.github.com/articles/syncing-a-fork/)

...and so on. [GitHub has a lot of great docs.](https://help.github.com/) StackOverflow has a lot of answers, too. I don't know of a specific tutorial.

**Pull request closed without merging**
